name: load_more_flutter
description: Load more data when scroll to end of ListView Flutter.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.5

  distinct_value_connectable_stream: ^1.1.0
  rxdart: ^0.24.0
  rx_redux: ^1.2.0
  disposebag: ^1.1.2

  collection: ^1.14.12
  tuple: ^1.0.3
  built_value: ^7.1.0
  built_collection: ^4.3.2
  cached_network_image: ^2.1.0+1
  http: ^0.12.0+4

#flutter packages pub run build_runner build

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/people.json
flutter_intl:
  enabled: true
